name: "Hashnode Blog Updater"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Runs Every Sunday

jobs:
  update_blogs:
    name: "Update Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "📚  Hashnode Updater"
        uses: "varunsridharan/action-hashnode-blog@main"
        with:
          USERNAME: 'arnabsen1729' # Hashnode Username
          BLOG_URL: 'https://arnabsen.dev/' # Blog URL
          COUNT: 5 # MAX Visisble
          STYLE: "blog-left"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
